### ISSUE TITLE
Full gherkin spec still missing (or undocumented)

### ISSUE THREAD

**Issue by dclucas** [sheerun/ava-spec#10]
Was having a look at using an xSpec (Jasmine-like) or xBehave (cucumber-like, AKA Gherkin) and noticed I wasn't able to use classic Gherkin keywords such as When/Then/And (to name a few of the most critical).

I had a look at the source code, but there's no mention to those keywords ("scenario" is also not listed, and seems to be just a naming convention for the first argument on the "feature" keyword), so my guess is that this is not implemented at all.

A full-blown cucumber-like syntax will probably be complex, so for the short term the most realistic thing to do is to remove that part of the readme and, if the effort seems worth it, put this in the backlog (more than happy to contribute a PR or two to help with that...).

**Comment by sheerun** [comment]
Sure, I'll accept a PR with tests
