### ISSUE TITLE
No 'describe' output in reporter

### ISSUE THREAD

**Issue by F1LT3R** [sheerun/ava-spec#15]
Hi there, firstly thanks for this library. It's a great add-on for Ava and I am finding it useful for converting mocha tests.

I'm expecting to see grouped reports like I do in mocha, eg:

```plaintext
Some feature
 - Test 1
 - Test 2
 - Test 3
```

There is no output of the text passed as the first argument to `describe`.

```javascript
import {describe} from 'ava-spec'
describe('This is not output to the reporter', it => {
  it('...but this is output', t => {
    t.pass()
  })
})
```

Note: I am executing the tests with the verbose reporter:

```shell
ava lib/**/*.spec.js --verbose
```
Am I doing something wrong? Should I expect to see `describe` text output in the reporter?

**Comment by sheerun** [comment]
Sorry I cannot reproduce. It work for me for current repository when I run for example `node_modules/.bin/ava spec --verbose`. Besides I've decided to deprecate this repository and point to [Jest](https://facebook.github.io/jest/) as it is more powerful and supports describe blocks out of the box.
