### ISSUE TITLE
`.only` and `.skip` support

### ISSUE THREAD

**Issue by iamstarkov** [sheerun/ava-spec#6]
first of all, thank you for ava-spec lib.

`.only` and `.skip` are useful and supported by ava, but couldnt get ava-spec to work with it.
what do you thinkg?

**Comment by tjbenton** [comment]
@iamstarkov These do currently work for me.

```js
const one = test.group('one');
one.skip('test', (t) => {
  t.pass();
});

test.group('two', (test) => {
  test.skip((t) => {
    t.pass();
  });
});
```


```js
test.group('only', (test) => {
  test("this won't run", (t) => {
    t.pass();
  });

  test.only('this is the only one that will run', (t) => {
    t.pass();
  });
});
```

**Comment by iamstarkov** [comment]
hmm

**Comment by iamstarkov** [comment]
i usually do like this and its not working for me:

```
import test from 'ava';
import { describe } from 'ava-spec';

describe('group for this file', () => {
  test('sup', t => {
    t.is(1, 1 );
  });

  test('js', t => {
    t.is(2, 2);
  })
});
```

and i have several files like this. run `ava --watch` and want to debug only these group, so i do `describe.only()` but its not working

**Comment by tjbenton** [comment]
That won't work because of the way that ava-spec works. This should work for you.

```js
import { describe } from 'ava-spec';

describe('group for this file', (test) => {
  test('sup', t => {
    t.is(1, 1 );
  });

  test('js', t => {
    t.is(2, 2);
  })
});
```

**Comment by iamstarkov** [comment]
im confused, if its not how ava-spec works, then why suggested code will work with `.skip/.only`?

**Comment by tjbenton** [comment]
You need to read the the [usage](https://github.com/sheerun/ava-spec#usage) where it talks about _Jasmine-like DSL is supported:_. `ava` and `ava-spec`don't use global variables like other testing libraries, you have to import the library in the test file and when you nest different tests it passes in the nested test function to the group(aka describe) function. In the README.md where it shows the jasmine like DLS example the `it` is actually the `test` function so you can use `it.only` or `it.skip`


Here are examples of a few different ways you can use it along with what their output is in the command line. I hope this helps clear up the confusion.

```js
import {describe} from 'ava-spec';

describe('AVA Spec', it => {
  it('This never runs', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.only('this is the only test that will run', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.todo('This todo never runs');
});
```

###### Result: 

![screen shot 2016-12-10 at 10 14 28 am](https://cloud.githubusercontent.com/assets/4776422/21074215/76d8836a-bec1-11e6-95fe-bfb7c68c70d5.jpg)



```js
import {describe} from 'ava-spec';

describe('This group never runs', it => {
  it('can look almost like jasmine', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.todo('supports all chaining modifiers!');
});


describe.only('These are the only tests that will run', it => {
  it('can look almost like jasmine', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.todo('supports all chaining modifiers!');
});
```

###### Result: 

![screen shot 2016-12-10 at 10 12 49 am](https://cloud.githubusercontent.com/assets/4776422/21074210/4a805e6e-bec1-11e6-948d-983ed061a085.jpg)



```js
import {describe} from 'ava-spec';

describe('group one', it => {
  it('can look almost like jasmine', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.todo('supports all chaining modifiers!');
});


describe('group two', it => {
  it('this will run', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it('this will run', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it.skip('this will be skipped', t => {
    t.deepEqual([1, 2], [1, 2]);
  });
});

describe.skip('group three', it => {
  it('this will be skipped because the parent describe has the `skip` on it', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it('this will be skipped because the parent describe has the `skip` on it', t => {
    t.deepEqual([1, 2], [1, 2]);
  });

  it('this will be skipped because the parent describe has the `skip` on it', t => {
    t.deepEqual([1, 2], [1, 2]);
  });
});
```

###### Result: 

![screen shot 2016-12-10 at 10 10 55 am](https://cloud.githubusercontent.com/assets/4776422/21074203/01192e22-bec1-11e6-98ee-c648ed572ba3.jpg)

**Comment by iamstarkov** [comment]
thanks
